services:
  ping-app:
    image: meter-read-api
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
      - ./lib:/app/lib
      - /app/venv
    restart: unless-stopped
    ports:
      - "5001:5001"
    # environment:
    #   - ENV_VAR=your_value              # Pass environment variables